# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 140, 13))
        self.label.setObjectName("label")
        self.song_title = QtWidgets.QLineEdit(self.centralwidget)
        self.song_title.setGeometry(QtCore.QRect(90, 30, 113, 20))
        self.song_title.setObjectName("song_title")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 60, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(220, 30, 80, 13))
        self.label_3.setObjectName("label_3")
        self.song_autor = QtWidgets.QLineEdit(self.centralwidget)
        self.song_autor.setGeometry(QtCore.QRect(310, 30, 113, 20))
        self.song_autor.setObjectName("song_autor")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 140, 13))
        self.label_4.setObjectName("label_4")
        self.orig_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.orig_text.setGeometry(QtCore.QRect(20, 150, 270, 340))
        self.orig_text.setObjectName("orig_text")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 120, 60, 13))
        self.label_5.setObjectName("label_5")
        self.trans_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.trans_text.setGeometry(QtCore.QRect(320, 150, 270, 340))
        self.trans_text.setObjectName("trans_text")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(320, 120, 120, 13))
        self.label_6.setObjectName("label_6")
        self.get_text = QtWidgets.QPushButton(self.centralwidget)
        self.get_text.setGeometry(QtCore.QRect(310, 70, 100, 23))
        self.get_text.setObjectName("get_text")
        self.pretty_flag = QtWidgets.QCheckBox(self.centralwidget)
        self.pretty_flag.setGeometry(QtCore.QRect(20, 60, 250, 20))
        self.pretty_flag.setObjectName("pretty_flag")
        self.info = QtWidgets.QLabel(self.centralwidget)
        self.info.setGeometry(QtCore.QRect(30, 500, 560, 13))
        self.info.setText("")
        self.info.setObjectName("info")
        self.error_text = QtWidgets.QLabel(self.centralwidget)
        self.error_text.setGeometry(QtCore.QRect(30, 520, 560, 20))
        self.error_text.setText("")
        self.error_text.setObjectName("error_text")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Проект 1"))
        self.label.setText(_translate("MainWindow", "Введите данные о песне:"))
        self.label_2.setText(_translate("MainWindow", "Название:"))
        self.label_3.setText(_translate("MainWindow", "Исполнитель:"))
        self.label_4.setText(_translate("MainWindow", "Полученный текст песни:"))
        self.label_5.setText(_translate("MainWindow", "Оригинал:"))
        self.label_6.setText(_translate("MainWindow", "Перевод на русский:"))
        self.get_text.setText(_translate("MainWindow", "Запрос текста"))
        self.pretty_flag.setText(_translate("MainWindow", "Красивый текст (без указания на припев)"))
